[theme]
base = "light"
primaryColor = "#3F654F"
backgroundColor = "#F5F2EB"
secondaryBackgroundColor = "#ECE8DE"
textColor = "#272922"
font = "sans-serif"
baseRadius = "medium"
buttonRadius = "medium"

[server]
headless = true
runOnSave = false
enableXsrfProtection = true
enableCORS = true
maxUploadSize = 25

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
